language: java
jdk: openjdk14
git:
  depth: false
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mboysan-github"

install: true   # skip default mvn commands

env:
  - COV_DIR="$TRAVIS_BUILD_DIR/jbizur-distribution/target/site/jacoco-aggregate/jacoco.xml"

jobs:
  include:
    - stage: test
      before_script:
        - mkdir ./config
        - mkdir ./log
        - chmod +x ./scripts/*
        - printenv
      script:
        - mvn -Dsonar.coverage.jacoco.xmlReportPaths=$COV_DIR -Dmaven.javadoc.skip=true -DcreateChecksum=true -V clean install sonar:sonar
      after_failure:
        - bash ./scripts/uploadlog.sh "jbizur-core/log"
        - bash ./scripts/uploadlog.sh "jbizur-bizur/log"
    - stage: deploy
      if: branch = master
      script:
        - bash ./scripts/deploy.sh