language: java
jdk: oraclejdk8
git:
  depth: false
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mboysan-github"

install: true   # skip default mvn commands

before_script:
  - mkdir ./config
  - mkdir ./config/log
  - chmod +x ./scripts/uploadlog.sh
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.javadoc.skip=true -DcreateChecksum=true -V
after_failure:
  - bash ./scripts/uploadlog.sh "config/log"