language: java
jdk: openjdk13
git:
  depth: false
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mboysan-github"

install: true   # skip default mvn commands

before_script:
  - mkdir ./config
  - mkdir ./log
  - chmod +x ./scripts/*
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.javadoc.skip=true -DcreateChecksum=true -V
#  - mvn clean install -DskipITs -Dmaven.javadoc.skip=true -DcreateChecksum=true -V
after_failure:
  - bash ./scripts/uploadlog.sh "log"
after_success:
  - bash ./scripts/deploy.sh