language: java
jdk: openjdk13
git:
  depth: false
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mboysan-github"

install: true   # skip default mvn commands

jobs:
  include:
    - stage: test
      before_script:
        - mkdir ./config
        - mkdir ./log
        - chmod +x ./scripts/*
      script:
#        - mvn -Dsonar.coverage.jacoco.xmlReportPaths=/home/travis/build/mboysan/jbizur/jbizur-distribution/target/site/jacoco-aggregate/jacoco.xml -Dmaven.javadoc.skip=true -DcreateChecksum=true -V clean install sonar:sonar
        - mvn -Dsonar.coverage.jacoco.xmlReportPaths=$TRAVIS_BUILD_DIR/jbizur-distribution/target/site/jacoco-aggregate/jacoco.xml -Dmaven.javadoc.skip=true -DcreateChecksum=true -V clean install sonar:sonar
      after_failure:
        - bash ./scripts/uploadlog.sh "jbizur-core/log"
        - bash ./scripts/uploadlog.sh "jbizur-bizur/log"
    - stage: deploy
      if: branch = master
      script:
        - bash ./scripts/deploy.sh