language: java
jdk: openjdk-ea
git:
  depth: false

#cache:
#  directories:
#    - '$HOME/.m2'
#    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mboysan-github"

#install: true   # skip default mvn commands

env:
  - COV_DIR="$TRAVIS_BUILD_DIR/jbizur-distribution/target/site/jacoco-aggregate/jacoco.xml"

jobs:
  include:
    - stage: test
      before_script:
        - echo "chmodding"
        - chmod +x ./scripts/*
        - echo "mkdiring config"
        - mkdir ./config
        - echo "mkdiring log"
        - mkdir ./log
        - echo "wgetting jdk"
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - echo "installing jdk"
        - source ./install-jdk.sh --verbose --feature ea
        - echo JAVA_HOME = ${JAVA_HOME}
        - echo PATH = ${PATH}
        - ls ${JAVA_HOME}
        - java -version
      script:
        - mvn -Dsonar.coverage.jacoco.xmlReportPaths=$COV_DIR -Dmaven.javadoc.skip=true -DcreateChecksum=true -V clean install sonar:sonar
      after_failure:
        - bash ./scripts/uploadlog.sh "jbizur-core/log"
        - bash ./scripts/uploadlog.sh "jbizur-bizur/log"
    - stage: deploy
      if: branch = master
      script:
        - bash ./scripts/deploy.sh